apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ngnx-deploy
  name: ngnx-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ngnx-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ngnx-deploy
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}
