apiVersion: v1
kind: Pod
metadata:
  labels:
    run: envvarwcmap
  name: envvarwcmap
spec:
  containers:
  - image: busybox:latest
    name: envvarwcmap
    args:
      - sleep
      - "3600"
    env:
      - name: PLANET
        valueFrom:
          configMapKeyRef:
            name: space
            key: planet
      - name: MOON
        valueFrom:
          configMapKeyRef:
            name: space
            key: moon
