apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podresourcequota
  name: podresourcequota
spec:
  containers:
  - image: busybox:latest
    name: podresourcequota
    args:
            - sleep
            - "3600"
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  #  nodeSelector:
  #        kind: special
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: run
                operator: In
                values:
                  - podsel
          topologyKey: kubernetes.io/hostname
status: {}
